version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:${NGINX_HTTP_HOST_PORT}"
      - "${NGINX_HTTPS_HOST_PORT}:${NGINX_HTTPS_HOST_PORT}"
      - "${NGINX_WEB_HOST_PORT}:${NGINX_WEB_HOST_PORT}"
      - "${NGINX_EXPOSE_HOST_PORT}:${NGINX_EXPOSE_HOST_PORT}"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    expose:
      - ${NGINX_EXPOSE}
    restart: always
    environment:
      TZ: "${TZ}"
    networks:
      customize:
        ipv4_address: "${IP_NGINX}"

  php-fpm:
    build:
      context: ./Service/php-fpm
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
    container_name: php-fpm
    ports:
      - "${Swoole_HOST_PORT}:${Swoole_HOST_PORT}"
      - "${Swoole_CENTER_HOST_PORT}:${Swoole_CENTER_HOST_PORT}"
      - "${Swoole_REDIRECT_HOST_PORT}:${Swoole_REDIRECT_HOST_PORT}"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php:rw
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    environment:
      TZ: "${TZ}"
    networks:
      customize:
        ipv4_address: "${IP_FPM}"

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_HOST_PORT}"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${TZ}"
    networks:
      customize:
        ipv4_address: "${IP_MySQL}"

  pma:
    depends_on:
      - mysql
    image: phpmyadmin/${PMA_VERSION}
    container_name: pma
    restart: always
    ports:
      - "${PMA_HOST_PORT}:${NGINX_HTTP_HOST_PORT}"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      TZ: "${TZ}"
    networks:
      customize:
        ipv4_address: "${IP_PMA}"

  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_HOST_PORT}"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: "${TZ}"
    networks:
      customize:
        ipv4_address: "${IP_REDIS}"

networks:
  customize:
    ipam:
      config:
        - subnet: "${IP_SUBNET}"
          gateway: "${IP_GATEWAY}"